---
- name: Restrict root Login - access.conf
  copy:
    src: access.conf
    dest: /etc/security/access.conf
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"
  register: rootlogin

- name: Restrict root Login - securetty
  copy:
    src: securetty
    dest: /etc/securetty
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"
  register: rootlogin