---

DOCKER_ROOT_PATH: /opt/minecraft
DOCKER_COMPOSE_LOCATION: "{{ DOCKER_ROOT_PATH }}/docker-compose.yml"
#

# Volumes
DOCKER_VOLUME_PATH: "{{ DOCKER_ROOT_PATH }}/volumes"
TRAEFIK_DOCKER_VOLUME_PATH: "{{ DOCKER_VOLUME_PATH }}/traefik"
MINECRAFT_DOCKER_VOLUME_PATH: "{{ DOCKER_VOLUME_PATH }}/minecraft"

TRAEFIK_CONFIG_PATH: "{{ TRAEFIK_DOCKER_VOLUME_PATH }}/traefik.yml"

MINECRAFT_DATA_PATH: "{{ MINECRAFT_DOCKER_VOLUME_PATH }}/data"
MINECRAFT_WORLD_PATH: "{{ MINECRAFT_DOCKER_VOLUME_PATH }}/worlds"
MINECRAFT_CONFIG_PATH: "{{ MINECRAFT_DOCKER_VOLUME_PATH }}/config"
